services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=moovilogdb
    volumes:
      - moovilog_pg_data:/bitnami/postgresql

volumes:
  moovilog_pg_data:
